name: Package and publish random-stuff

on:
  push:
    branches:
      - 'main'
    paths:
      - src/**
      - public/**
      - index.html
      - Dockerfile
      - .dockerignore
      - tsconfig.app.json
      - vite.config.ts
      - nginx.conf
      - package.json
      - package-lock.json
      - .github/workflows/build-and-publish.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: '${{github.repository}}:${{ github.sha }}'

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          platforms: linux/amd64,linux/arm64
